# Name : msunpv_addons_thermostats.yaml
# Addons pour afficher les consigne et hystérésis des thermostats du MsunPv.
#
# Ne pas oublier de remplacer IP_DU_MSUNPV par l'adresse ip de votre MsunPv partout où c'est nécessaire dans le fichier.


### Récupération des données
rest:
  - resource: http://IP_DU_MSUNPV/param.xml?typmod=4
    scan_interval: 600
    method: GET
    sensor:
      - name: "msunpv_thermostats_xml"
        json_attributes_path: "$.xml"
        value_template: "OK"
        json_attributes:
          - "parMod0"
          - "parMod1"
          - "parMod2"
          
### Tous les sensors créés avec mise en forme des données
template:
  - sensor:
      - name: msunpv_consign_th_1 #Consigne thermostat 1
        unique_id: "msunpv_consign_th_1"
        state: >-
          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod0')|replace(";1;1","")).split(":")[0]).split(";")[1] |float /10 }}
        unit_of_measurement: "W"
          
      - name: msunpv_hyster_th_1 #Hysteresis Thermostat 1
        unique_id: "msunpv_hyster_th_1"
        state: >-
          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod0')|replace(";1;1","")).split(":")[1]).split(";")[1] |float /10 }}
        unit_of_measurement: "W"
        
      - name: msunpv_consign_th_2 #Consigne thermostat 2
        unique_id: "msunpv_consign_th_2"
        state: >-
          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod1')|replace(";1;1","")).split(":")[0]).split(";")[1] |float /10 }}
        unit_of_measurement: "°C"
          
      - name: msunpv_hyster_th_2 #Hysteresis Thermostat 2
        unique_id: "msunpv_hyster_th_2"
        state: >-
          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod1')|replace(";1;1","")).split(":")[1]).split(";")[1] |float /10 }}
        unit_of_measurement: "°C"
        
      - name: msunpv_consign_th_3 #Consigne thermostat 3
        unique_id: "msunpv_consign_th_3"
        state: >-
          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod2')|replace(";1;1","")).split(":")[0]).split(";")[1] |float /10 }}
        unit_of_measurement: "°C"
          
      - name: msunpv_hyster_th_3 #Hysteresis Thermostat 3
        unique_id: "msunpv_hyster_th_3"
        state: >-
          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod2')|replace(";1;1","")).split(":")[1]).split(";")[1] |float /10 }}
        unit_of_measurement: "°C"

#      - name: msunpv_consign_th_4 #Consigne thermostat 4
#        unique_id: "msunpv_consign_th_4"
#        state: >-
#          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod3')|replace(";1;1","")).split(":")[0]).split(";")[1] |float /10 }}
#        unit_of_measurement: "W"
#          
#      - name: msunpv_hyster_th_4 #Hysteresis Thermostat 4
#        unique_id: "msunpv_hyster_th_4"
#        state: >-
#          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod3')|replace(";1;1","")).split(":")[1]).split(";")[1] |float /10 }}
#        unit_of_measurement: "W"
#        
#      - name: msunpv_consign_th_5 #Consigne thermostat 5
#        unique_id: "msunpv_consign_th_5"
#        state: >-
#          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod4')|replace(";1;1","")).split(":")[0]).split(";")[1] |float /10 }}
#        unit_of_measurement: "°C"
#          
#      - name: msunpv_hyster_th_5 #Hysteresis Thermostat 5
#        unique_id: "msunpv_hyster_th_5"
#        state: >-
#          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod4')|replace(";1;1","")).split(":")[1]).split(";")[1] |float /10 }}
#        unit_of_measurement: "°C"
#        
#      - name: msunpv_consign_th_6 #Consigne thermostat 6
#        unique_id: "msunpv_consign_th_6"
#        state: >-
#          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod5')|replace(";1;1","")).split(":")[0]).split(";")[1] |float /10 }}
#        unit_of_measurement: "°C"
#          
#      - name: msunpv_hyster_th_6 #Hysteresis Thermostat 6
#        unique_id: "msunpv_hyster_th_6"
#        state: >-
#          {{ ((state_attr('sensor.msunpv_thermostats_xml', 'parMod5')|replace(";1;1","")).split(":")[1]).split(";")[1] |float /10 }}
#        unit_of_measurement: "°C"

shell_command:
  msunpv_enable_thermostats: "curl http://IP_DU_MSUNPV/param.htm?typmod=4"

automation:
  - id: 'msunpv_update_thermostats'
    alias: msunpv - Mise à jour affichage thermostats
    description: "Force un refresh de msunpv_thermostats_xml après avoir charger le page correspondante du routeur à l'aide de la shell_command.msunmsunpv_enable_thermostatspv_enable_progh."
    trigger:
    - platform: state
      entity_id:
      - sensor.msunpv_consign_th_1
      to: unavailable
      for:
        hours: 0
        minutes: 2
        seconds: 0
    condition: []
    action:
    - service: shell_command.msunpv_enable_thermostats
      data: {}
    - delay:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - service: homeassistant.update_entity
      data: {}
      target:
        entity_id: sensor.msunpv_thermostats_xml
    mode: single
